spring:
  datasource:
    initialize: true
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: postgres
    password: postgres
    
app: 
  ticket: 
    holdExpiryTime: 2 #This is configured in minutes
    reserveAlDone: Already made the reservation with the same hold id 
    reserveErrorCd: 410
    emailError: Email is different from what enetered while holding the seat
    emailErrorCd: 411
    holdExpired: Hold is already expired
    holdExprCd: 412
    noFullReqSeatsAvl: Requested Seats are not fully Available
    noReqSeatsAvl: Requested Seats are not Available.
    seatsAvlErrorCd: 413
    genError: Service is unavailable now 
    genErrorCode: 500