spring:
  datasource:
    initialize: true
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: postgres
    password: postgres
    
  jmx: 
    default-domain: TicketApp
    
app: 
  ticket: 
    holdExpiryTime: 2 #This is configured in minutes
    reserveAlDone: Already made the reservation with the same hold id 
    reserveErrorCd: 410
    emailError: Email is different from what enetered while holding the seat
    emailErrorCd: 411
    holdExpired: Hold Id is expired or not valid
    holdExprCd: 412
    noFullReqSeatsAvl: Requested Seats are not fully Available
    noReqSeatsAvl: Requested Seats are not Available.
    seatsAvlErrorCd: 413
    genError: Service is unavailable now 
    genErrorCode: 500
    requestNull: Service request is not valid
    requestNullErrorCd: 400
    emailIdNull: Email Id is required
    emailIdNullErrorCd: 401
    numSeatsNotValid: numSeats should be greater than 0
    numSeatsNotValidErrorCode: 402
    minLevelNotValid: minLevel should be greater than 0
    minLevelNotValidErrorCode: 403
    maxLevelNotValid: maxLevel should be greater than 0
    maxLevelNotValidErrorCode: 404
    minLevelHigherMaxLevel : minLevel should be less than or equal to maxLevel
    minLevelHigherMaxLevelErrorCd: 405
    minMaxLevelLimit: LevelIds are not valid
    minMaxLevelLimitErrorCd: 406
    seatHoldNotValid: seatHoldId should be greater than 0
    seatHoldNotValidErrorCode: 407
    emailIdNotValid: Email Id is not valid
    emailIdNotValidErrorCd: 408
    
logging:    
   level:
     com:
      ticket: 'DEBUG'
   file: logs/ticketapp.log
          
      